[paths.download]
path = "~/Downloads/App Installers"

[paths.desktop]
path = "~/.local/share/applications"

[apps.zen]
name = "zen"
base_dir = "~/.local/share/zen"
latest_release_url = "https://api.github.com/repos/zen-browser/desktop/releases/latest"
# optional
user_data_dir = "~/.zen" # not used, just for reference
icon = "zen"

[apps.heroic]
name = "heroic"
base_dir = "~/.local/share/heroic"
latest_release_url = "https://api.github.com/repos/Heroic-Games-Launcher/HeroicGamesLauncher/releases/latest"
version_file = "~/.local/share/heroic/heroic.desktop"
user_data_dir = "~/.config/heroic"
icon = "~/.local/share/heroic/resources/app.asar.unpacked/build/icon-light.png"

[apps.protonup]
name = "protonup"
base_dir = "~/.local/share/protonup"
latest_release_url = "https://api.github.com/repos/DavidoTek/ProtonUp-Qt/releases/latest"

[apps.peazip]
name = "peazip"
base_dir = "~/.local/share/peazip"
latest_release_url = "https://api.github.com/repos/ferion11/PeaZip_Appimage/releases/latest"

[apps.missioncenter]
name = "missioncenter"
base_dir = "~/.local/share/missioncenter"
latest_release_url = "https://gitlab.com/api/v4/projects/mission-center-devs%2Fmission-center/releases/permalink/latest"

[apps.audacity]
name = "audacity"
base_dir = "~/.local/share/audacity"
latest_release_url = "https://api.github.com/repos/audacity/audacity/releases/latest"

[apps.nvtop]
name = "nvtop"
base_dir = "~/.local/share/nvtop"
latest_release_url = "https://api.github.com/repos/Syllo/nvtop/releases/latest"

[apps.opencode]
name = "opencode"
base_dir = "~/.local/share/opencode"
latest_release_url = "https://api.github.com/repos/anomalyco/opencode/releases/latest"
